global:
  scrape_interval: 15s  # 메트릭 데이터를 수집하는 간격

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Prometheus 자체 메트릭

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:9323']  # cAdvisor 메트릭